version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  json:
    format: "%(asctime)s"
    class: pythonjsonlogger.jsonlogger.JsonFormatter

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  api_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/api.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf8
  
  training_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/training.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf8
  
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  "":  # root logger
    level: INFO
    handlers: [console, file]
    propagate: false
  
  src.api:
    level: INFO
    handlers: [console, api_file]
    propagate: false
  
  src.models:
    level: INFO
    handlers: [console, training_file]
    propagate: false
  
  src.data:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  src.features:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  src.monitoring:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  uvicorn:
    level: INFO
    handlers: [console, api_file]
    propagate: false
  
  uvicorn.access:
    level: INFO
    handlers: [api_file]
    propagate: false
  
  mlflow:
    level: WARNING
    handlers: [console]
    propagate: false

root:
  level: INFO
  handlers: [console, file, error_file]